language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t satyadocker1/docker-react -f Dockerfile.dev .


script: 
  - docker run -e CI=true satyadocker1/docker-react npm run test
